import Foundation
import SwiftData

/// Represents a historical running workout extracted from Apple HealthKit.
/// Persisted locally via SwiftData.
@Model
final class RunRecord {
    /// A unique identifier for the run record in SwiftData.
    @Attribute(.unique) var id: UUID

    /// The original HKWorkout UUID from HealthKit.
    var hkWorkoutID: UUID

    /// The start date and time of the run.
    var date: Date

    /// The total distance covered during the run, stored in meters.
    var totalDistanceMeters: Double

    /// The total duration of the run, stored in seconds.
    var duration: TimeInterval

    // MARK: - Raw Metrics (from Apple Health)
    /// Raw average pace (seconds/km)
    var rawAvgPace: Double
    /// Raw average heart rate (BPM)
    var rawAvgHeartRate: Double
    /// Raw average cadence (SPM)
    var rawAvgCadence: Double

    // MARK: - Framboise Working Metrics
    /// True working distance excluding dead stops (meters)
    var workingDistanceMeters: Double?
    /// True working duration excluding dead stops (seconds)
    var workingDurationSeconds: Double?
    /// Whether the workout was performed indoors (e.g., treadmill)
    var isIndoor: Bool?
    /// True working average pace, excluding dead stops (seconds/km)
    var workingAvgPace: Double
    /// True working average cadence (SPM)
    var workingAvgCadence: Double
    /// True working average heart rate (BPM)
    var workingAvgHeartRate: Double
    /// True working average vertical oscillation (cm)
    var workingAvgVerticalOscillation: Double?
    /// Raw average vertical oscillation (cm)
    var rawAvgVerticalOscillation: Double?

    var effectiveWorkingDistanceMeters: Double {
        workingDistanceMeters ?? totalDistanceMeters
    }

    var effectiveWorkingDurationSeconds: Double {
        workingDurationSeconds ?? duration
    }

    // MARK: - Framboise Mathematical Features
    /// Coefficient of variation for pace (sigma / mu)
    var paceCV: Double
    /// Linear regression slope of pace over time
    var paceSlope: Double
    /// Fraction of time spent in Zone 4
    var percentZone4: Double

    // MARK: - Classification & Tags
    /// The deterministic or CoreML predicted run type
    var detectedTypeRaw: String
    /// Tags generated by the Framboise engine (e.g., urbanTraffic, fatigue Drift)
    var framboiseTags: [String]

    // MARK: - AI Coaching
    /// A one-to-one relationship to the AI-generated coaching insight.
    /// Retained from v1.1 for structured drill display in V2 UI.
    @Relationship(deleteRule: .cascade, inverse: \CoachingInsight.runRecord)
    var insight: CoachingInsight?

    init(
        id: UUID = UUID(),
        hkWorkoutID: UUID,
        date: Date,
        totalDistanceMeters: Double,
        duration: TimeInterval,
        rawAvgPace: Double,
        rawAvgHeartRate: Double,
        rawAvgCadence: Double,
        workingAvgPace: Double,
        workingAvgCadence: Double,
        workingAvgHeartRate: Double,
        workingAvgVerticalOscillation: Double? = nil,
        rawAvgVerticalOscillation: Double? = nil,
        workingDistanceMeters: Double? = nil,
        workingDurationSeconds: TimeInterval? = nil,
        isIndoor: Bool? = nil,
        paceCV: Double,
        paceSlope: Double,
        percentZone4: Double,
        detectedTypeRaw: String,
        framboiseTags: [String] = [],
        insight: CoachingInsight? = nil
    ) {
        self.id = id
        self.hkWorkoutID = hkWorkoutID
        self.date = date
        self.totalDistanceMeters = totalDistanceMeters
        self.duration = duration
        self.rawAvgPace = rawAvgPace
        self.rawAvgHeartRate = rawAvgHeartRate
        self.rawAvgCadence = rawAvgCadence
        self.workingAvgPace = workingAvgPace
        self.workingAvgCadence = workingAvgCadence
        self.workingAvgHeartRate = workingAvgHeartRate
        self.workingAvgVerticalOscillation = workingAvgVerticalOscillation
        self.rawAvgVerticalOscillation = rawAvgVerticalOscillation
        self.workingDistanceMeters = workingDistanceMeters
        self.workingDurationSeconds = workingDurationSeconds
        self.isIndoor = isIndoor
        self.paceCV = paceCV
        self.paceSlope = paceSlope
        self.percentZone4 = percentZone4
        self.detectedTypeRaw = detectedTypeRaw
        self.framboiseTags = framboiseTags
        self.insight = insight
    }
}
