import Foundation
import SwiftData

/// Represents a historical running workout extracted from Apple HealthKit.
/// Persisted locally via SwiftData.
@Model
final class RunRecord {
    /// A unique identifier for the run record in SwiftData.
    @Attribute(.unique) var id: UUID

    /// The original HKWorkout UUID from HealthKit.
    var hkWorkoutID: UUID

    /// The start date and time of the run.
    var date: Date

    /// The total distance covered during the run, stored in meters.
    var totalDistanceMeters: Double

    /// The total duration of the run, stored in seconds.
    var duration: TimeInterval

    // MARK: - Raw Metrics (from Apple Health)
    /// Raw average pace (seconds/km)
    var rawAvgPace: Double
    /// Raw average heart rate (BPM)
    var rawAvgHeartRate: Double
    /// Raw average cadence (SPM)
    var rawAvgCadence: Double

    // MARK: - Framboise Working Metrics
    /// True working distance excluding dead stops (meters)
    var workingDistanceMeters: Double?
    /// True working duration excluding dead stops (seconds)
    var workingDurationSeconds: Double?
    /// Whether the workout was performed indoors (e.g., treadmill)
    var isIndoor: Bool?
    /// True working average pace, excluding dead stops (seconds/km)
    var workingAvgPace: Double
    /// True working average cadence (SPM)
    var workingAvgCadence: Double
    /// True working average heart rate (BPM)
    var workingAvgHeartRate: Double
    /// True working average vertical oscillation (cm)
    var workingAvgVerticalOscillation: Double?
    /// Raw average vertical oscillation (cm)
    var rawAvgVerticalOscillation: Double?

    var effectiveWorkingDistanceMeters: Double {
        workingDistanceMeters ?? totalDistanceMeters
    }

    var effectiveWorkingDurationSeconds: Double {
        workingDurationSeconds ?? duration
    }

    // MARK: - Framboise Mathematical Features
    /// Coefficient of variation for pace (sigma / mu)
    var paceCV: Double
    /// Linear regression slope of pace over time
    var paceSlope: Double
    /// Fraction of time spent in Zone 4
    var percentZone4: Double

    // MARK: - Classification & Tags
    /// The deterministic or CoreML predicted run type
    var detectedTypeRaw: String
    /// Tags generated by the Framboise engine (e.g., urbanTraffic, fatigue Drift)
    var framboiseTags: [String]

    // MARK: - AI Coaching
    /// A one-to-one relationship to the AI-generated coaching insight.
    /// Retained from v1.1 for structured drill display in V2 UI.
    @Relationship(deleteRule: .cascade, inverse: \CoachingInsight.runRecord)
    var insight: CoachingInsight?

    init(
        id: UUID = UUID(),
        hkWorkoutID: UUID,
        date: Date,
        totalDistanceMeters: Double,
        duration: TimeInterval,
        rawAvgPace: Double,
        rawAvgHeartRate: Double,
        rawAvgCadence: Double,
        workingAvgPace: Double,
        workingAvgCadence: Double,
        workingAvgHeartRate: Double,
        workingAvgVerticalOscillation: Double? = nil,
        rawAvgVerticalOscillation: Double? = nil,
        workingDistanceMeters: Double? = nil,
        workingDurationSeconds: TimeInterval? = nil,
        isIndoor: Bool? = nil,
        paceCV: Double,
        paceSlope: Double,
        percentZone4: Double,
        detectedTypeRaw: String,
        framboiseTags: [String] = [],
        insight: CoachingInsight? = nil
    ) {
        self.id = id
        self.hkWorkoutID = hkWorkoutID
        self.date = date
        self.totalDistanceMeters = totalDistanceMeters
        self.duration = duration
        self.rawAvgPace = rawAvgPace
        self.rawAvgHeartRate = rawAvgHeartRate
        self.rawAvgCadence = rawAvgCadence
        self.workingAvgPace = workingAvgPace
        self.workingAvgCadence = workingAvgCadence
        self.workingAvgHeartRate = workingAvgHeartRate
        self.workingAvgVerticalOscillation = workingAvgVerticalOscillation
        self.rawAvgVerticalOscillation = rawAvgVerticalOscillation
        self.workingDistanceMeters = workingDistanceMeters
        self.workingDurationSeconds = workingDurationSeconds
        self.isIndoor = isIndoor
        self.paceCV = paceCV
        self.paceSlope = paceSlope
        self.percentZone4 = percentZone4
        self.detectedTypeRaw = detectedTypeRaw
        self.framboiseTags = framboiseTags
        self.insight = insight
    }
}

extension RunRecord {
    /// Computes the duration-weighted 30-day baseline cadence strictly prior to this run's date from a collection of runs.
    func computeHistoricalBaselineCadence(in runs: [RunRecord]) -> Double? {
        guard let thirtyDaysAgo = Calendar.current.date(byAdding: .day, value: -30, to: self.date) else { return nil }
        let priorRuns = runs.filter {
            $0.date < self.date &&
            $0.date >= thirtyDaysAgo &&
            $0.workingAvgCadence > 0
        }
        guard !priorRuns.isEmpty else { return nil }
        let totalDuration = priorRuns.map(\.duration).reduce(0, +)
        guard totalDuration > 0 else {
            return priorRuns.map(\.workingAvgCadence).reduce(0, +) / Double(priorRuns.count)
        }
        return priorRuns.map { $0.workingAvgCadence * $0.duration }.reduce(0, +) / totalDuration
    }

    /// Computes the duration-weighted 30-day baseline cadence strictly prior to this run's date using its SwiftData ModelContext.
    func computeHistoricalBaselineCadence() -> Double? {
        guard let context = self.modelContext else { return nil }
        let runDate = self.date
        guard let thirtyDaysAgo = Calendar.current.date(byAdding: .day, value: -30, to: runDate) else { return nil }
        let descriptor = FetchDescriptor<RunRecord>(
            predicate: #Predicate<RunRecord> {
                $0.date < runDate && $0.date >= thirtyDaysAgo
            }
        )
        guard let priorRuns = try? context.fetch(descriptor) else { return nil }
        return computeHistoricalBaselineCadence(in: priorRuns)
    }
}
